### ISSUE TITLE
chapter 2评论系统的表单提交后，提交内容依然在表单里面

### ISSUE THREAD

**Issue by OneChin** [minkolee/django2-by-example-ZH#1]

**Comment by OneChin** [comment]
提交评论后，内容在表单里面，在刷新的话就又添加一次相同的评论。
原来的post_detail逻辑改为这样:
```
if request.method == POST:
    comment_form = CommemtForm(data=request.POST)
    ....后面逻辑不变
        new_comment.save()
#去掉else:
comment_form = CommentForm()
return render(...后面不变)
```
如果是POST内容，保存评论后就再重置一次表单，如果是GET请求，原来的逻辑不变。
在分享页面的时候，也是if POST, else GET，这种逻辑结构，但是HTML页面用if sent来处理了，表单不会再加载，所以没有问题。这个业务逻辑需要保存表单，就不能这么写。
还有一种写法是表单提交完就redirect的，但是没有相处来怎么写。
如果有更好的处理办法还望赐教。

**Comment by minkolee** [comment]
没错，自己修改为返回新表单对象即可。
