### ISSUE TITLE
item['price'] * item['quantity'] 会报错

### ISSUE THREAD

**Issue by topsai** [minkolee/django2-by-example-ZH#18]
https://github.com/minkolee/django2-by-example-ZH/blob/526b5591274740f0682fb52f5fd2af566477e69c/chapter07.html#L496

因为item['price'] 是字符串， item['quantity'] 是整数，做完乘法再强制转换成Decimal，就报错了，该行应该改为：
sum(Decimal(item['price']) * item['quantity'] for item in self.cart.values())

**Comment by minkolee** [comment]
感谢, 已经更改
