### ISSUE TITLE
Chapter 4 的 urlpatterns 问题

### ISSUE THREAD

**Issue by JohnZhu04** [minkolee/django2-by-example-ZH#4]
2.3 登录与登出视图中使用内置视图添加的 path 中的 `login` 和 `logout` 后少了 `/` 符号；

以及以下 path 也有这样的问题：
- 2.4 中的 `password_change` 
- 2.5 中的 `reset/<uidb64>/<token>`

**Comment by minkolee** [comment]
可加可不加，为了严谨我改一下了。
