### ISSUE TITLE
前四章一些小错误

### ISSUE THREAD

**Issue by odddriver** [minkolee/django2-by-example-ZH#6]
第一章 3设计博客应用的数据架构（data schema）Post模型中
 publish = models.DateTimeField(default=timezone.now())
应该是publish = models.DateTimeField(default=timezone.now)

第四章 5.1使用Google第三方认证 中
AUTHENTICATION_BACKENDS = [
    'social_core.backends.facebook.FacebookAppOAuth2',
]
应该是 'social_core.backends.google.GoogleOAuth2'

重定向网址少了个-
http://mysite.com:8000/socialauth/complete/google-oauth2/
==》
http://mysite.com:8000/social-auth/complete/google-oauth2/

**Comment by minkolee** [comment]
第一个问题里timezone.now是正确的，原来理解错误。
第二个问题已经修改
