### ISSUE TITLE
Chapter 7 和 8 的一些勘误

### ISSUE THREAD

**Issue by JohnZhu04** [minkolee/django2-by-example-ZH#8]
#### Chapter 7
- 2.4 
Cart `add()` 方法代码未缩进。

- 2.6.2
`<a href="{% url 'cart:cart_detail' %}">{{ total_items }} items{{ total_items|pluralize }}` 中 filter 前的 `items` 应为 `item` 。

#### Chapter 8
- 2.1 
    - `为此先来修改orders应用中的admin.py韦健` 中的 `韦健` 应为 `文件`。
    - 代码中的`exprot_to_csv` 拼写错误，应为 `export` 。

- 4.3 
    - `编辑orders应用的urls.py文件，为视图配置URL` 处`path('admin/order/<int:order_id</pdf/',views.admin_order_pdf,name='admin_order_pdf'),
]` 中 url 错误。
    - `order_pdf` 方法中 `<a href="{}">View</a>` 的 `View` 应为 `PDF` 。

**Comment by minkolee** [comment]
All problems has been corrected. Thank you very much.
