### ISSUE TITLE
无法在项目下urls.py注册app的urls请教

### ISSUE THREAD

**Issue by ghost** [minkolee/django2-by-example-ZH#9]
你好,请问下: 如果我创立了一个app叫做abc,那么项目下urls.py注册app的urls该怎么写? 测试了很多次但没成功.

"""moneydavis URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
 此处该如何写?

urlpatterns = [
      path('admin/', admin.site.urls),
      此处该如何写?
    
  
]

**Comment by minkolee** [comment]
首先:
1 abc先要注册到settings.py中
2 abc的目录下边要有urls.py
3 abc里设置app_name变量

然后在根urls.py中：
from django.urls import path,include
from abc import urls as abc_url
urlpatterns = [
    path('', include(abc_url, namespace='abc')),
]

namespace的名称要和app_name对应起来。其实官网文档说的很详细了，可以参考一下。

**Comment by ghost** [comment]
已经解决了, 因为第二点,新建立的app下面没有urls.py, 随便新增并加入了点东西就解决了.
另外这个可以不用from abc import urls as abc_url

直接写成:
urlpatterns: path('abc/', include('abc.urls')) 就可以了, 主要是参考第三个,当然如果你设置变量也可以,以后调用方便把?
Including another URLconf
1. Import the include() function: from django.urls import include, path
2. Add a URL to urlpatterns: path('blog/', include('blog.urls'))
